### ISSUE TITLE
Using the k8s deployment #5

### ISSUE THREAD

**Issue by hli12345** [Anaconda-Platform/ae5-tools#111] opened 2020-02-06 21:21 UTC
"ae5 session list --k8s" command works for a non-admin username but fails for an admin id. 

It may not be related to role differences, but to the fact that we have hundreds of sessions (400+) in the env. 

ae5 session list --k8s 
Error: Unexpected response: 414 Request-URI Too Large
  GET https://k8s.wwwdesign.anaconda.ford.com/pods?id=a1-04... (id=project_id&id=...)
  headers: {'Server': 'nginx', 'Date': 'Thu, 06 Feb 2020 21:12:58 GMT', 'Content-Type': 'text/html', 'Content-Length': '186', 'Connection': 'close', 'Strict-Transport-Security': 'max-age=2592000; preload'}
  text: <html>
<head><title>414 Request-URI Too Large</title></head>
<body bgcolor="white">
<center><h1>414 Request-URI Too Large</h1></center>
<hr><center>nginx</center>
</body>
</html>

2nd error: 
Using an Admin accout to run "ae5 session list --k8s --filter owner=hli1" to filter on a normal username gives the same error.

**Comment by mcg1969** [comment] 2020-02-07 15:25
OK, so I don't have any experience with this many sessions. It seems clear what the issue is: the GET URI is too large, because it has one `id=` argument for each session. We should use the POST approach instead so these ids can be delivered in the body instead of the URI.

**Comment by mcg1969** [comment] 2020-02-14 04:50
@hli12345 I do believe we have fixed this in the latest PR. Assuming the master branch tests pass and the package is built we should try the Dev build on your cluster.

**Comment by mcg1969** [comment] 2020-02-14 04:51
But note that it will require redeployment of the k8s deployment. We can still test with SSH mode though. In fact, I have rewritten SSH mode to pass everything through a local server instance to make sure we can fully test everything.

**Comment by mcg1969** [comment] 2020-07-28 23:34
Should be fixed by #122. This is a client-side only fix so it should not be necessary to update your k8s deployment.

**Closed** 2020-07-28 23:34 UTC
